version: '2.4'

services:
  zk:
    image: zookeeper:3.5
    restart: always
    environment:
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
