version: '2.4'

# Ideally, this replication mode should not be deployed on the same physical machine
# let's allow this for development and for proof of concept.
# Reference: https://hub.docker.com/_/zookeeper, 
# https://zookeeper.apache.org/doc/current/zookeeperStarted.html#sc_RunningReplicatedZooKeeper
services:
  zoo1:
    extends: 
      file: common.yml
      service: zk
    hostname: zoo1
    ports:
     - "2181:2181"
    environment:
      ZOO_MY_ID: 1

  zoo2:
    extends: 
      file: common.yml
      service: zk
    hostname: zoo2
    ports:
     - "2182:2181"
    environment:
      ZOO_MY_ID: 2

  zoo3:
    extends: 
      file: common.yml
      service: zk
    hostname: zoo3
    ports:
     - "2183:2181"
    environment:
      ZOO_MY_ID: 3
