[general]
pidfile="/etc/run/burrow.pid"
stdout-logfile="/etc/log/burrow.out"
access-control-allow-origin="*"

[logging]
filename="/etc/run/burrow.log"
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=[{ZOOKEEPER_SERVERS}]
timeout=6
root-path="/burrow"

[cluster.instigator]
class-name="kafka"
servers=[{KAFKA_BROKERS}] # assuming 3 brokers within the cluster
topic-refresh=60
offset-refresh=30

[consumer.instigator]
class-name="kafka"
cluster="instigator"
servers=[{KAFKA_BROKERS}] # assuming 3 brokers within the cluster
offsets-topic="__consumer_offsets"
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"
group-whitelist=""

[consumer.instigator_zk]
class-name="kafka_zk"
cluster="instigator"
servers=[{ZOOKEEPER_SERVERS}]
zookeeper-path={ZOOKEEPER_PATH}
zookeeper-timeout=30
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"
group-whitelist=""

[httpserver.default]
address=":8000"

[storage.default]
class-name="inmemory"
workers=20
intervals=15
expire-group=604800
min-distance=1
